### ISSUE TITLE
[Problem report] It gives an error for an USB drive on every start up

### ISSUE THREAD

**Issue by theoware** [aleksey-hoffman/sigma-file-manager#2]
## System info:
- **App version**: `1.0.0` 
- **Operating System**: `x64 | Windows 10`

## Problem:
```
Error: Error: EISDIR, Das GerÃ¤t ist nicht bereit.
 'F:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)
```
Note: If trying to use it in Windows explorer it says: Please insert drive.

**Comment by aleksey-hoffman** [comment]
Thank you. The problem is fixed.
I will release the update today.
