### ISSUE TITLE
App will stop on welcome page(win11)

### ISSUE THREAD

**Issue by Own-lin** [aleksey-hoffman/sigma-file-manager#222]
### Is there an existing issue for this?

- [X] I have searched the opened issues

### Problem description

I'm trying to use this app (.exe) on Windows 11, but it doesn't seem to open on my computer.
>  .exe is same as Microsoft Store
![image](https://user-images.githubusercontent.com/58496860/221909021-3dbde3cc-d267-4577-b9d2-6b1a27d889e6.png)

I will provide on-site DUMP files URL：
[.DMP file](https://foreign-common-1301944092.cos.ap-hongkong.myqcloud.com/Sigma%20file%20manager%20%282%29.DMP)

### Steps to reproduce

1. open this app

### Environment

- OS: Windows11 (22623.1325)
- App version: 1.6

- CPU:	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
- RAM:	16.0 GB (15.4 GB )

**Comment by aleksey-hoffman** [comment]
Thanks for the report!
Please provide some more information so I can fix it:

- Open the app;
- Press `Ctrl + Shift + I` to open the developer tools;
- Switch to the `Console` tab
- If you see any red errors, please show me the screenshot

**Comment by Own-lin** [comment]
> 感谢您的报告！ 请提供更多信息，以便我修复它：
> 
> * 打开应用程序；
> * 按`Ctrl + Shift + I`打开开发者工具；
> * 切换到`Console`选项卡
> * 如果您看到任何红色错误，请给我看截图

**Yes, the ‘console‘’ has fed back some errors. I took screenshots of some errors：**

![image](https://user-images.githubusercontent.com/58496860/222018711-730463c6-6652-4381-bfe9-b0f906eee2f4.png)

_And save this error to this  file:_
[https://foreign-common-1301944092.cos.ap-hongkong.myqcloud.com/.-1677632448824.log](error.log)

**Comment by tasi788** [comment]
same.

## Environment
OS: Windows11 (22000.1574)
App version: 1.6
CPU: i9-9900KF with RTX 3060Ti
RAM: 32.0 GB

## Error Output
```node:events:505 Uncaught Error: write EPIPE
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_errnoException (node:internal/errors:595:12)
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:817:11)
    at Socket._write (node:net:829:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Writable.write (node:internal/streams/writable:334:10)
    at r._runCommand (reusableCli.js:124:26)
    at reusableCli.js:119:12
    at new Promise (<anonymous>)
    at r._execQueueCommand (reusableCli.js:85:12)
    at r._scheduleCommand (reusableCli.js:75:12)
    at r.exec (reusableCli.js:37:10)
    at ActionToolbarBase.vue?9739:272:17
    at new Promise (<anonymous>)
    at u (ActionToolbarBase.vue?9739:271:10)
    at m (ActionToolbarBase.vue?9739:284:3)
    at ActionToolbarBase.vue?9739:53:9
    at r.init (reusableCli.js:22:7)```
