### ISSUE TITLE
[Auto-generated problem report] unhandled error

### ISSUE THREAD

**Issue by CalebCao9420** [aleksey-hoffman/sigma-file-manager#312]
## System info:
- **App version**: 1.7.0
- **App page**: navigator
- **Operating System**: x64, win32, 10.0.22631
- **Free memory**: 10.4 GB
### Error:
```js
TypeError: Cannot read properties of null (reading 'addedIndex')

    at app://./js/chunk-vendors.33a9c220.js:229:172960

    at Object.handleDrop (app://./js/chunk-vendors.33a9c220.js:229:181297)

    at app://./js/chunk-vendors.33a9c220.js:229:166409

    at t (app://./js/chunk-vendors.33a9c220.js:229:164954)

    at app://./js/chunk-vendors.33a9c220.js:229:165200

```
### App action history:
```js
10:18:27:051 | App.vue::initAllStorageFiles()
10:18:28:288 | store.js::UPDATE_STORAGE_FILE()
11:23:14:808 | store.js::UPDATE_STORAGE_FILE()
11:23:14:838 | App.vue::initAllStorageFiles()
11:23:15:295 | store.js::UPDATE_STORAGE_FILE()
11:23:15:822 | store.js::UPDATE_STORAGE_FILE()
11:23:15:836 | App.vue::initAllStorageFiles()
11:23:16:302 | store.js::UPDATE_STORAGE_FILE()
11:23:18:863 | store.js::UPDATE_STORAGE_FILE()
11:23:18:875 | App.vue::initAllStorageFiles()
11:23:19:294 | store.js::UPDATE_STORAGE_FILE()
11:23:19:869 | store.js::UPDATE_STORAGE_FILE()
11:23:19:899 | App.vue::initAllStorageFiles()
11:23:20:301 | store.js::UPDATE_STORAGE_FILE()
11:34:59:487 | store.js::UPDATE_STORAGE_FILE()
11:34:59:504 | App.vue::initAllStorageFiles()
11:35:00:287 | store.js::UPDATE_STORAGE_FILE()
11:35:00:491 | store.js::UPDATE_STORAGE_FILE()
11:35:00:509 | App.vue::initAllStorageFiles()
11:35:01:299 | store.js::UPDATE_STORAGE_FILE()
11:51:14:695 | store.js::UPDATE_STORAGE_FILE()
11:51:14:712 | App.vue::initAllStorageFiles()
11:51:15:300 | store.js::UPDATE_STORAGE_FILE()
11:51:15:706 | store.js::UPDATE_STORAGE_FILE()
11:51:15:722 | App.vue::initAllStorageFiles()
11:51:15:841 | App.vue::initAllStorageFiles()
11:51:16:296 | store.js::UPDATE_STORAGE_FILE()
11:51:17:216 | store.js::UPDATE_STORAGE_FILE()
11:51:17:256 | App.vue::initAllStorageFiles()
11:51:18:302 | store.js::UPDATE_STORAGE_FILE()
11:51:19:334 | store.js::UPDATE_STORAGE_FILE()
11:51:19:346 | App.vue::initAllStorageFiles()
11:51:20:293 | store.js::UPDATE_STORAGE_FILE()
11:51:20:343 | store.js::UPDATE_STORAGE_FILE()
11:51:20:359 | App.vue::initAllStorageFiles()
11:51:21:291 | store.js::UPDATE_STORAGE_FILE()
12:21:28:753 | store.js::UPDATE_STORAGE_FILE()
12:21:28:765 | App.vue::initAllStorageFiles()
12:21:29:292 | store.js::UPDATE_STORAGE_FILE()
12:21:29:759 | store.js::UPDATE_STORAGE_FILE()
12:21:29:773 | App.vue::initAllStorageFiles()
12:21:30:301 | store.js::UPDATE_STORAGE_FILE()
14:09:10:024 | store.js::UPDATE_STORAGE_FILE()
14:09:10:053 | App.vue::initAllStorageFiles()
14:09:11:031 | store.js::UPDATE_STORAGE_FILE()
14:09:11:052 | App.vue::initAllStorageFiles()
14:09:11:303 | store.js::UPDATE_STORAGE_FILE()
14:45:10:834 | store.js::loadDir()
14:45:12:228 | store.js::loadDir()
14:45:17:436 | store.js::UPDATE_STORAGE_FILE()

```

**Comment by CalebCao9420** [comment]
Thanks, docker build with error after auto issue commit. I thought commit
will failed. But to hear back from you ,it looks like it worked

Aleksey Hoffman ***@***.***> 于2024年1月17日周三 02:32写道：
