### ISSUE TITLE
Problem: No Drives show up; Windows

### ISSUE THREAD

**Issue by Joester202** [aleksey-hoffman/sigma-file-manager#36]
Error: Error: EISDIR, The device is not ready.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)

**Comment by krsagarts** [comment]
Yep...same for me

**Comment by lukasong** [comment]
+1

**Comment by OfficialEsco** [comment]
Duplicate of #1

**Comment by aleksey-hoffman** [comment]
Thank you. The problem is fixed.
I will release the update today.
