### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by Steve1150** [aleksey-hoffman/sigma-file-manager#49]
I get the following error when launching: 
"Error: Error: EISDIR, The device is not ready.
 'E:/'
    at o.fetchStorageDevices (app://./index.bundle.js:1:48802)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async o.mounted (app://./index.bundle.js:1:22620)"
This happens when a disc drive without media is present...
I can still use the program however and does not prevent me from performing anything specific.

**Comment by aleksey-hoffman** [comment]
Thanks, the problem is already fixed.
I will publish an update today / tomorrow

**Comment by Steve1150** [comment]
Thanks for the info!
